import type { RecordId } from './entities.js';

export const DIAGNOSTIC_CODES_V1 = [
  'TS_PARSE_ERROR',
  'TS_IMPORT_UNRESOLVED',
  'NEST_ROUTE_DYNAMIC',
  'NEST_CUSTOM_ROUTE_DECORATOR',
  'NEST_GUARD_UNRESOLVED',
  'DI_TOKEN_UNSUPPORTED',
  'CALL_TARGET_UNRESOLVED',
  'CALL_DEPTH_LIMIT',
  'AUTH_GLOBAL_POLICY_UNKNOWN',
  'TYPEORM_ENTITY_UNRESOLVED',
  'TYPEORM_OPERATION_UNSUPPORTED',
  'TYPEORM_SAVE_COLUMNS_UNKNOWN',
] as const;
export const DIAGNOSTIC_CODES_V2 = [
  ...DIAGNOSTIC_CODES_V1,
  'NEST_MODULE_METADATA_UNRESOLVED',
  'NEST_GLOBAL_GUARD_UNRESOLVED',
  'NEST_BOOTSTRAP_GUARD_UNRESOLVED',
  'TYPEORM_QUERY_BUILDER_STATE_AMBIGUOUS',
  'TYPEORM_QUERY_BUILDER_FLOW_UNSUPPORTED',
  'TYPEORM_QUERY_BUILDER_TABLE_UNRESOLVED',
  'TYPEORM_QUERY_BUILDER_TERMINAL_MISSING',
  'TYPEORM_RAW_SQL_DIALECT_UNSELECTED',
  'TYPEORM_RAW_SQL_RECEIVER_AMBIGUOUS',
  'TYPEORM_RAW_SQL_SOURCE_UNSUPPORTED',
  'TYPEORM_RAW_SQL_LIMIT_EXCEEDED',
  'TYPEORM_RAW_SQL_PARSE_FAILED',
  'TYPEORM_RAW_SQL_STATEMENT_UNSUPPORTED',
  'REQUEST_PROVENANCE_UNSUPPORTED',
  'REQUEST_PROVENANCE_LIMIT_EXCEEDED',
  'REQUEST_PROVENANCE_INTER_METHOD_UNSUPPORTED',
  'REQUEST_PROVENANCE_CALL_DEPTH_LIMIT',
] as const;
export const DIAGNOSTIC_CODES_V3 = [
  ...DIAGNOSTIC_CODES_V2,
  'OUTBOUND_HTTP_TARGET_DYNAMIC',
  'OUTBOUND_HTTP_METHOD_DYNAMIC',
  'OUTBOUND_HTTP_CONFIG_UNSUPPORTED',
  'OUTBOUND_HTTP_RECEIVER_UNSUPPORTED',
  'OUTBOUND_HTTP_TARGET_LIMIT_EXCEEDED',
  'OUTBOUND_HTTP_ACTIVATION_UNKNOWN',
  'INTERACTION_RECEIVER_AMBIGUOUS',
  'INTERACTION_TARGET_DYNAMIC',
  'INTERACTION_TRACE_LIMIT_REACHED',
  'INTERACTION_CYCLE_TRUNCATED',
  'EVENT_EMITTER_CONFIGURATION_UNKNOWN',
  'EVENT_HANDLER_REGISTRATION_UNKNOWN',
  'JOB_QUEUE_HANDLER_REGISTRATION_UNKNOWN',
  'JOB_QUEUE_FILTER_UNPROVEN',
  'MICROSERVICE_TRANSPORT_UNKNOWN',
  'MICROSERVICE_TRANSPORT_MISMATCH',
  'MICROSERVICE_ACTIVATION_UNKNOWN',
  'MICROSERVICE_HANDLER_REGISTRATION_UNKNOWN',
  'MICROSERVICE_REQUEST_HANDLER_AMBIGUOUS',
] as const;
export const DIAGNOSTIC_CODES_V4 = [...DIAGNOSTIC_CODES_V3, 'JOB_QUEUE_FILTER_PARTIAL'] as const;
export const DIAGNOSTIC_CODES_V5 = [
  ...DIAGNOSTIC_CODES_V4,
  'AUTHORIZATION_METADATA_VALUE_DYNAMIC',
  'AUTHORIZATION_ENFORCEMENT_UNKNOWN',
] as const;
export const DIAGNOSTIC_CODES_V6 = [
  ...DIAGNOSTIC_CODES_V5,
  'RESOURCE_ACCESS_TARGET_DYNAMIC',
  'RESOURCE_ACCESS_TARGET_LIMIT_EXCEEDED',
  'RESOURCE_ACCESS_OPERATION_UNSUPPORTED',
] as const;
export const DIAGNOSTIC_CODES_V7 = [
  ...DIAGNOSTIC_CODES_V6,
  'CRITICAL_SECTION_TARGET_DYNAMIC',
  'CRITICAL_SECTION_TARGET_LIMIT_EXCEEDED',
  'CRITICAL_SECTION_CALLBACK_UNSUPPORTED',
] as const;
export const DIAGNOSTIC_CODES_V8 = [
  ...DIAGNOSTIC_CODES_V7,
  'CRITICAL_SECTION_CALLBACK_FLOW_UNPROVEN',
  'CRITICAL_SECTION_WRAPPER_TARGET_AMBIGUOUS',
  'CRITICAL_SECTION_WRAPPER_CYCLE_TRUNCATED',
  'CRITICAL_SECTION_WRAPPER_LIMIT_REACHED',
] as const;
export const DIAGNOSTIC_CODES = DIAGNOSTIC_CODES_V8;
export type DiagnosticCode = (typeof DIAGNOSTIC_CODES)[number];

export const DIAGNOSTIC_SEVERITIES = ['info', 'warning', 'error'] as const;
export type DiagnosticSeverity = (typeof DIAGNOSTIC_SEVERITIES)[number];

export interface DiagnosticRecord {
  readonly id: RecordId;
  readonly code: DiagnosticCode;
  readonly severity: DiagnosticSeverity;
  readonly message: string;
  readonly subjectId?: RecordId | undefined;
  readonly evidenceIds: readonly RecordId[];
}
